export const postsArr = [
    {
        date: "June 06, 2024",
        title: "Quiting Coding Strike",
        content: "Today, I am breaking my coding strike. I've been on vacation, and when I came back it was hard to code. Today I will become passionate again. I am working on finishing a liking feature on my compliments project. I need it to sync with firebase. I am thinking of using the firebase keys for the compliment to associate them appropriately.",
        image: "./images/ilya-pavlov-monitor-with-code.jpg",
        alt: "A computer monitor with what looks like php code on it.",
        id: "1",
    },
    {
        date: "June 07, 2024",
        title: "Tired of Learning New Things",
        content: "Today I am feeling overwelmed but excited. I don't want to work, I want to code. I am joining a course that will review the modules (one per week). We are starting with module one today. I am overwelmed with the lack of desire I have to do the learning portion, and instead wanting to fix my broken projects. I want to fix my notes site, which is not displaying the content since I moved each section to separate html files and can't get them to show up on the main html file. I've been told it's not possible to place html files within eachother. I am thinking of using .innerhtml but I am sure it won't work. I also need to fix the lists app. I was creating a way to add numbers, and it would add them together, including negatives, but now that I'm separating the lists I am rethinking how I'll do that. I think I will have a separate input section for the numbers. I was unable to fix the liking feature on the compliments app. I could not get it to update on firebase. I also realized I could have merged the lists in firebase, so I might want to refactor the whole app. All and all I am pretty overwhelmed.",
        image: "./images/christin-hume-person-at-laptop.jpg",
        alt: "A woman in a gray shirt sitting at a table outside on a laptop.",
        id: "2",
    },
    {
        date: "June 21, 2024",
        title: "Uphill Battle",
        content: "Forgot to write these, but I finally remembered two weeks later! I keep going off and just building stuff with everything I'm learning. I think in the long run it will help cement the information I've learned. I just learned about forEach and I really wanna use it in some of the old code I have. I might. Not today though. Today I learn. I'm getting through the JS module five I think. It's been an uphill battle. When I finished the pumpkins purrrfect meme loader I went off on a little tangent and changed it to be a place I can put images of my pets then load a random picture of a pet based on which pet I select. You can check it out <a href='https://pet-pic-picker.netlify.app/'>at my netlify site 'Pet Pics'</a>. The issue I have run into is I don't know how to upload an image. Or, where to upload it too? I'm hoping react will cover this. I really don't feel ready for any back end learning, so I hope I don't have to go there to understand it. You can check the code out at <a href='https://github.com/Raehale/pet-pic-picker' target='_blank'>my Github</a>. Overall I'm doing good, got back up from a little not wanting to code struggle and feeling better then ever. Also, I would like the record to show, even though I didn't always do what I was supposed to, I did code every day even if I didn't write about it.",
        image: "./images/mitchell-orr-uphill.jpg",
        alt: "A woman hiking up a grassy hill.",
        id: "3",
    },
    {
        date: "July 16, 2024",
        title: "Back to it",
        content: "I have been coding I swear, I code so much. I'm so tired. At least I got back to this before it had been a whole month! Small wins! Now I will have a platform for this though. I am making a new site, it's called Learning Journal. I am supposed to have a bunch of posts on it, and since I want it to be unique, I will write the posts. Coding has been good. I got pretty depressed for a while there, but luckily my coding buddy, Fadumo, kept me in line and I coded every day. Every. Single. Day. Which is a good thing, but I won't lie, I miss my free time. That's ok, it was actually pretty fun coding last night. I was just learning but I finished a module and am ending it with this solo project. Things are looking up, go team!!",
        image: "./images/awmleer-I--person-at-laptop.jpg",
        alt: "A man sitting in the dark on a laptop.",
        id: "4",
    },
    {
        date: "July 18, 2024",
        title: "Grid is Hard",
        content: "Still working on the Learning Journal project. I am really struggling with getting the posts on the home page to display as a grid. Flex would be so much easier, but since the whole module was about grid I'm sure I am supposed to use grid. Plus it'll help me learn it if I use it. But it is driving me insane. I also think I'm gonna make the posts look a little different, add a background, maybe a border, and have them display like a collage. That's all for today",
        image: "./images/sarandy-westfall-photos.jpg",
        alt: "A man sitting in the dark on a laptop.",
        id: "5",
    },
    {
        date: "July 19, 2024",
        title: "I Have a Plan",
        content: "Today I am still working on the Learning Journal. I am making a page that loads the post information from the post the user clicked. I am hopeful I can do this fairly easily. We'll see though, knock on wood for me. I've also been working with my team (Guiseppe and Fadumo) to create the Best Bank app. I think we're collaborating really well! I feel like I'm coming out of the rut and getting back into coding as my passion, which is good because I really need this to work out. No pressure or anything! I am excited to move on from the Learning Journal though. There's this advanced javascript course I get to try out that I am super excited and equally nervous about doing. I'm also nervous about how short my posts are. I just don't have too much to say each day. I am not very chatty, and what I'm doing feels pretty straight forward... To complete todays task I am going to use the ids for each object within the array and put it on the element as a data attribute, than grab that data attribute. After I have that I'll find which object has the id and load the information from there. We'll see if that works! After I load all the correct information I have to be sure to load three recent posts that are not the post that I just loaded. I've also never made a site with multiple pages like this. I feel like it must be pretty straight forward but who knows. Anyways, here goes it!",
        image: "./images/kelly-sikkema-sticky-notes.jpg",
        alt: "A man sitting in the dark on a laptop.",
        id: "6",
    },
    {
        date: "July 20, 2024",
        title: "Javascript Reads Down",
        content: "The home page is broken for some reason and I don't know how to change the URLs for pages which feels like something I should know how to do by now! So today I will fix the home page, which seems to be an issue with a piece of code not running that shouldn't run on that page so I just have to stop it from running on that page. I'd also like to organize all the code by page, but that could create issues with the code that is used more than once. AFter I fix that, I want to find out how to give the pages better urls than index.html. I imagine that'll come in handy to know some day. Then I want to finish the about me page. The code that's breaking the home page is what I want to run on the about me page, but it runs before the page is loaded then when the page is loaded it disapears. I think it's because I have it running after someone clicks the link button. I think it'll fix both issues if I run the function within an if statement saying if an element that is on the about page exists, run this code. Then I will move on to the portfolio page. I'm going to go through my repos (Currently 21) and take screenshots and store all the information in an array. I want to link to their netlify sites too. I think it'll be pretty straight forward. If I have any time left I will submit my journal (I might wait until I don't have any placeholder info) and begin the advanced javascript course I said I'd test.",
        image: "./images/dylan-gillis-laptop-on-table.jpg",
        alt: "A laptop sitting on a octogonal wooden table in the dark with a cacti in front of it food and a cup to it's left and a bottle to it's right.",
        id: "7",
    },
    {
        date: "July 22, 2024",
        title: "Final Touches on the Learning Journal",
        content: "I forgot to log it but I totally coded yesterday. Today I am still working on the Learning Journal. I don't like the hover effect on the header so I'd like to change that. Maybe blur the image instead of make it black and white, and make the header slightly larger. Still workshopping that. I'd also like to make the hover on the posts slightly less subtle Just darker colors should work. For the About page I need to make sure the selected post doesn't show up in the recent posts. I am not sure why it isn't working, I have it set to if (postId !== selectedPostId) but it shows it anyways. I'll have to think about that one. I also want a little more space between the photo and header information. In the footer I'd like to add some contact information. On the portfolio, I almost kind of got the grid to work but it breaks the further down you scroll. It's trying to get the images to fit but I don't want it to destroy the image to make it fit. Grid is still not my forte so I'm not sure how to fix this. I want to style it too. I'm thinking jsut the images, no borders, with a title at the top and the tags at the bottom. Not sure what to do about getting the title to be viewable though. I need a background, but that looks cheap. I also want to center the last post when it's on tablet view. After that I'd say the project is done. I'd just need one more entry for it to look alright. Then I have to try to keep up posting here. If I get done with time to spare I will start the advanced Javascript.",
        image: "./images/muhammad-rahim-person-painting.jpg",
        alt: "A man sitting in the dark on a laptop.",
        id: "8",
    },
    {
        date: "July 23, 2024",
        title: "Cleaning Up",
        content: "I am done! Now all I need to do is clean up my mess. This project is so messy! I need to merge my data files into data.js, and update the references, be sure to import/export the portfolio array from data.js instead of projects.js. Then I need to separate the pages js files. I think I can do this by using the export/import feature to keep the data I need to transfer. That way I can get rid of all the if(this exists) run code nonesense. After that I need a good once over for my javascript. I think I did a good job but I'm sure there's lets that could be consts and other stuff that I'll be called out for on the review. Then I want to review the html files. I'm thinking I'll put the html that the JS puts in in the file, but comment it out, so it's easier to read, not sure yet though. Then I need to go over the css. This one needs a lot of work. I should go through and create classes that cover everything so I can combine them and keep DRYer code. I really don't want to but I also really don't want the reviewer to have to explain stuff I already know and just didn't do because of laziness. After that I can submit! I'll even have no more placeholder content as this is the last post I need to replace that! When I submit it, I will ask for a few things. First, I want to know how to make the pathname different than index.html. It can't be that complex right? Then I want to see if there's a better way to do my grid layout on my portfolio page. It's just not quite right. I also might change the background color on the pages, it looks weird with my portfolio images. Then I want to know if there's a way to make what I did with the hove effect on the portfolio items accessible, because I know it's not but :focus doesn't work. I have also just reaslised that portfolio is not mobile first. I will make it mobile first and work from there.",
        image: "./images/cdc-cleaning.jpg",
        alt: "A person mopping the floor of a house.",
        id: "9",
    },
    {
        date: "July 24, 2024",
        title: "Lots of Learning",
        content: "All I plan to do today is the advanced javascript course. I will say, it's really hard. Advanced is no joke it's brutal. I've learned about default exporting and name exporting. I learned about setInterval and setTimer and how to use them. I learned about the Javascript runtime environment and how it goes from the heap, to the call stack, if it requires time it enters the WebAPI which holds it until the time out out. Once the time is over it is sent to the bottom of the task queue. The task queue will then send the code to the call stack once the event loop says the call stack is ready. I also learned about the performance.now() thing that returns a really accurate timestamp. I also learned about ++Pre-increment and --Pre-decrement which are super cool and if you put ++ or -- at the front of an expression and it will increment or decrement the variables value before the result is gotten. I'm really excited for that one but I'm not sure why since I can't think of a time I've needed that. I will say if I do get to use it it's gonna feel so good to know about it. I learned more about constructors. The error constructor is cool and if you put the throw keyword before it it will stop all the code following from running. How cool is that! I have used the date constructor before, it's actually used on this site for the footer year. Then there are other constructors, String(), Number(), Array(), and Boolean() which is less useful than using the litteral. I'm excited to learn more!",
        image: "./images/corina-rainer-notes.jpg",
        alt: "An open notebook with notes in it and a notepad laying on top.",
        id: "10",
    },
    // {
    //     date: "",
    //     title: "",
    //     content: "",
    //     image: "",
    //     alt: "",
    //     id: "",
    // },
]

export const projectsArr = [
    {
        name: "Rat Counter",
        github: "https://github.com/Raehale/rat-counter",
        link: "https://dazzling-taffy-b72679.netlify.app/",
        screenshot: "./projects/rat-counter.jpg",
        description: "An app for a user to count how many rats they see each day.",
        id: 1,
        tags: ["CSS", "HTML", "Javascript", "App"],
        size: "wide",
        date: "May 5, 2024",
    },
    {
        name: "Business Card",
        github: "https://github.com/Raehale/business-card",
        link: "https://business-card-raehaley.netlify.app/",
        screenshot: "./projects/business-card.jpg",
        description: "A small business card sized site displaying my information.",
        id: 11,
        tags: ["CSS", "HTML", "Website"],
        size: "wide",
        date: "May 6, 2024",
    },
    {
        name: "Happy Birthday Site",
        github: "https://github.com/Raehale/happy-birthday-site",
        link: "https://gentle-bienenstitch-a31d58.netlify.app/",
        screenshot: "./projects/birthday-gifts.jpg",
        description: "A website displaying birthday GIFts for my rats.",
        id: 2,
        tags: ["CSS", "HTML", "Website"],
        size: "normal",
        date: "May 7, 2024",
    },
    {
        name: "Home Town",
        github: "https://github.com/Raehale/home-town",
        link: "https://aquamarine-empanada-f3f2ed.netlify.app/",
        screenshot: "./projects/Visit-Missoula-MT-USA.jpg",
        description: "A website advertising my home town.",
        id: 3,
        tags: ["CSS", "HTML", "Website"],
        size: "wide",
        date: "May 9, 2024",
    },
    {
        name: "Score Board",
        github: "https://github.com/Raehale/score-board",
        link: "https://gilded-starship-91d8a9.netlify.app/",
        screenshot: "./projects/Score-Board.jpg",
        description: "An app that tracks the scores of two teams.",
        id: 4,
        tags: ["CSS", "HTML", "Javascript", "App"],
        size: "box",
        date: "May 15, 2024",
    },
    {
        name: "Password Generator",
        github: "https://github.com/Raehale/password-generator",
        link: "https://moonlit-belekoy-587d28.netlify.app/",
        screenshot: "./projects/Generate-a-Random-Password.jpg",
        description: "An app that randomly generates a password.",
        id: 13,
        tags: ["CSS", "HTML", "Javascript", "App"],
        size: "box",
        date: "May 19, 2024",
    },
    {
        name: "Tabs Tracker",
        github: "https://github.com/Raehale/tab-tracker",
        link: "chrome://extensions/?id=hombgpfeadgajodedjjgjjeihmgbokkk",
        screenshot: "./projects/tab-saver.jpg",
        description: "A google extention that creates a list of sites you add to it to review later.",
        id: 14,
        tags: ["CSS", "HTML", "Javascript", "Extension"],
        size: "wide",
        date: "May 23, 2024",
    },
    {
        name: "Unit Conversion",
        github: "https://github.com/Raehale/unit-conversion",
        link: "https://fluffy-gumption-cfc0a9.netlify.app/",
        screenshot: "./projects/unit-convertor.jpg",
        description: "An app that converts Metric and Imperial units.",
        id: 12,
        tags: ["CSS", "HTML", "Javascript", "App"],
        size: "wide",
        date: "May 24, 2024",
    },
    {
        name: "Notes Site",
        github: "https://github.com/Raehale/notes-site",
        link: "https://scrimba-code-notes.netlify.app/",
        screenshot: "./projects/Study-Notes.jpg",
        description: "A website displaying all my notes.",
        id: 6,
        tags: ["CSS", "HTML", "Javascript", "Website"],
        size: "tall",
        date: "May 26, 2024",
    },
    {
        name: "Add To List",
        github: "https://github.com/Raehale/add-to-list",
        link: "https://add-to-list-raehaley.netlify.app/",
        screenshot: "./projects/Add-to-List.jpg",
        description: "An app using firebase to create and manage a list. It will have multiple list options.",
        id: 7,
        tags: ["CSS", "HTML", "Javascript", "WIP", "App"],
        size: "tall",
        date: "June 1, 2024",
    },
    {
        name: "Endorsements",
        github: "https://github.com/Raehale/endorsements",
        link: "https://endorsements-raehaley.netlify.app/",
        screenshot: "./projects/champions.png",
        description: "A firebase app where users can write an endorsement to another user.",
        id: 10,
        tags: ["CSS", "HTML", "Javascript", "App"],
        size: "box",
        date: "June 7, 2024",
    },
    {
        name: "Oldagram",
        github: "https://github.com/Raehale/oldagram",
        link: "https://lively-syrniki-b7d7af.netlify.app/",
        screenshot: "./projects/Oldagram.jpg",
        description: "A site showing the old version of instagram.",
        id: 9,
        tags: ["CSS", "HTML", "Javascript", "WIP", "App"],
        size: "tall",
        date: "June 9, 2024",
    },
    {
        name: "Pet Pic Picker",
        github: "https://github.com/Raehale/pet-pic-picker",
        link: "https://pet-pic-picker.netlify.app/",
        screenshot: "./projects/Pet-Pics.jpg",
        description: "An app you can upload images of your pets and it will randomly generate a pet from the one you selected.",
        id: 8,
        tags: ["CSS", "HTML", "Javascript", "WIP", "App"],
        size: "box",
        date: "June 19, 2024",
    },
    {
        name: "Twitter Copy",
        github: "https://github.com/Raehale/twitter-copy",
        link: "https://twitter-copy-rae.netlify.app/",
        screenshot: "./projects/twitter-sux.jpg",
        description: "A copy of twitter with a login ability.",
        id: 5,
        tags: ["CSS", "HTML", "Javascript", "WIP", "App"],
        size: "normal",
        date: "June 22, 2024",
    },
    {
        name: "Mobile Restaurant Menu",
        github: "https://github.com/Raehale/mobile-restaurant-menu",
        link: "https://mobile-restaurant-menu-raehaley.netlify.app/",
        screenshot: "./projects/restaurant-menu.jpg",
        description: "An app for ordering from a restaurant, paying, and leaving a review.",
        id: 16,
        tags: ["CSS", "HTML", "Javascript", "App"],
        size: "normal",
        date: "June 29, 2024",
    },
    {
        name: "Best Fictional Rat",
        github: "https://github.com/Raehale/best-fictional-rat",
        link: "https://best-fictional-rat.netlify.app/",
        screenshot: "./projects/best-fictional-rat.jpg",
        description: "A website made mobile first giving an award for best fictional rat.",
        id: 15,
        tags: ["CSS", "HTML", "Website"],
        size: "normal",
        date: "July 13, 2024",
    },
    {
        name: "Ratify Me",
        github: "https://github.com/Raehale/ratify-me",
        link: "https://ratify-me.netlify.app/",
        screenshot: "./projects/Ratify-Me.jpg",
        description: "It will work as a site that adds a random rat image to an image you upload.",
        id: 17,
        tags: ["CSS", "HTML", "WIP", "App"],
        size: "wide",
        date: "July 15, 2024",
    },
    {
        name: "Rat News",
        github: "https://github.com/Raehale/Rat-News",
        link: "https://rat-news.netlify.app/",
        screenshot: "./projects/RatNews.jpg",
        description: "A website displaying fake articles about rats to display a grid layout.",
        id: 18,
        tags: ["CSS", "HTML", "Website"],
        size: "wide",
        date: "July 15, 2024",
    },
    {
        name: "Best bank",
        github: "https://github.com/Raehale/Best-Bank",
        link: "https://best-bank-group.netlify.app/",
        screenshot: "./projects/Best-Bank.jpg",
        description: "This is a group project done with two others, Fadumo and Guiseppe, that displays a bank statement page.",
        id: 20,
        tags: ["CSS", "HTML", "Javascript", "Website", "WIP", "Group"],
        size: "wide",
        date: "July 15, 2024",
    },
    {
        name: "Learning Journal",
        github: "https://github.com/Raehale/Learning-Journal",
        link: "https://learning-journal-rh.netlify.app/",
        screenshot: "./projects/My-Learning-Journal.jpg",
        description: "A simple website to show my journey as a front end developer.",
        id: 19,
        tags: ["CSS", "HTML", "Javascript", "Website"],
        size: "box",
        date: "July 19, 2024",
    },
    // {
    //     name: "",
    //     github: "",
    //     link: "",
    //     screenshot: "",
    //     description: "",
    //     id: "",
    //     tags: [],
    //     size: ["normal"],
    //     date: "July 19, 2024",
    // },
]