export const postsArr = [
    {
        date: "June 06, 2024",
        title: "Quiting Coding Strike",
        content: "Today, I am breaking my coding strike. I've been on vacation, and when I came back it was hard to code. Today I will become passionate again. I am working on finishing a liking feature on my compliments project. I need it to sync with firebase. I am thinking of using the firebase keys for the compliment to associate them appropriately.",
        image: "./images/ilya-pavlov-monitor-with-code.jpg",
        alt: "A computer monitor with what looks like php code on it.",
        id: "1",
    },
    {
        date: "June 07, 2024",
        title: "Tired of Learning New Things",
        content: "Today I am feeling overwelmed but excited. I don't want to work, I want to code. I am joining a course that will review the modules (one per week). We are starting with module one today. I am overwelmed with the lack of desire I have to do the learning portion, and instead wanting to fix my broken projects. I want to fix my notes site, which is not displaying the content since I moved each section to separate html files and can't get them to show up on the main html file. I've been told it's not possible to place html files within eachother. I am thinking of using .innerhtml but I am sure it won't work. I also need to fix the lists app. I was creating a way to add numbers, and it would add them together, including negatives, but now that I'm separating the lists I am rethinking how I'll do that. I think I will have a separate input section for the numbers. I was unable to fix the liking feature on the compliments app. I could not get it to update on firebase. I also realized I could have merged the lists in firebase, so I might want to refactor the whole app. All and all I am pretty overwhelmed.",
        image: "./images/christin-hume-person-at-laptop.jpg",
        alt: "A woman in a gray shirt sitting at a table outside on a laptop.",
        id: "2",
    },
    {
        date: "June 21, 2024",
        title: "Uphill Battle",
        content: "Forgot to write these, but I finally remembered two weeks later! I keep going off and just building stuff with everything I'm learning. I think in the long run it will help cement the information I've learned. I just learned about forEach and I really wanna use it in some of the old code I have. I might. Not today though. Today I learn. I'm getting through the JS module five I think. It's been an uphill battle. When I finished the pumpkins purrrfect meme loader I went off on a little tangent and changed it to be a place I can put images of my pets then load a random picture of a pet based on which pet I select. You can check it out <a href='https://pet-pic-picker.netlify.app/'>at my netlify site 'Pet Pics'</a>. The issue I have run into is I don't know how to upload an image. Or, where to upload it too? I'm hoping react will cover this. I really don't feel ready for any back end learning, so I hope I don't have to go there to understand it. You can check the code out at <a href='https://github.com/Raehale/pet-pic-picker' target='_blank'>my Github</a>. Overall I'm doing good, got back up from a little not wanting to code struggle and feeling better then ever. Also, I would like the record to show, even though I didn't always do what I was supposed to, I did code every day even if I didn't write about it.",
        image: "./images/mitchell-orr-uphill.jpg",
        alt: "A woman hiking up a grassy hill.",
        id: "3",
    },
    {
        date: "July 16, 2024",
        title: "Back to it",
        content: "I have been coding I swear, I code so much. I'm so tired. At least I got back to this before it had been a whole month! Small wins! Now I will have a platform for this though. I am making a new site, it's called Learning Journal. I am supposed to have a bunch of posts on it, and since I want it to be unique, I will write the posts. Coding has been good. I got pretty depressed for a while there, but luckily my coding buddy, Fadumo, kept me in line and I coded every day. Every. Single. Day. Which is a good thing, but I won't lie, I miss my free time. That's ok, it was actually pretty fun coding last night. I was just learning but I finished a module and am ending it with this solo project. Things are looking up, go team!!",
        image: "./images/awmleer-I--person-at-laptop.jpg",
        alt: "A man sitting in the dark on a laptop.",
        id: "4",
    },
    {
        date: "July 18, 2024",
        title: "Grid is Hard",
        content: "Still working on the Learning Journal project. I am really struggling with getting the posts on the home page to display as a grid. Flex would be so much easier, but since the whole module was about grid I'm sure I am supposed to use grid. Plus it'll help me learn it if I use it. But it is driving me insane. I also think I'm gonna make the posts look a little different, add a background, maybe a border, and have them display like a collage. That's all for today",
        image: "./images/sarandy-westfall-photos.jpg",
        alt: "A man sitting in the dark on a laptop.",
        id: "5",
    },
    {
        date: "July 19, 2024",
        title: "I Have a Plan",
        content: "Today I am still working on the Learning Journal. I am making a page that loads the post information from the post the user clicked. I am hopeful I can do this fairly easily. We'll see though, knock on wood for me. I've also been working with my team (Guiseppe and Fadumo) to create the Best Bank app. I think we're collaborating really well! I feel like I'm coming out of the rut and getting back into coding as my passion, which is good because I really need this to work out. No pressure or anything! I am excited to move on from the Learning Journal though. There's this advanced javascript course I get to try out that I am super excited and equally nervous about doing. I'm also nervous about how short my posts are. I just don't have too much to say each day. I am not very chatty, and what I'm doing feels pretty straight forward... To complete todays task I am going to use the ids for each object within the array and put it on the element as a data attribute, than grab that data attribute. After I have that I'll find which object has the id and load the information from there. We'll see if that works! After I load all the correct information I have to be sure to load three recent posts that are not the post that I just loaded. I've also never made a site with multiple pages like this. I feel like it must be pretty straight forward but who knows. Anyways, here goes it!",
        image: "./images/kelly-sikkema-sticky-notes.jpg",
        alt: "A man sitting in the dark on a laptop.",
        id: "6",
    },
    {
        date: "July 20, 2024",
        title: "Javascript Reads Down",
        content: "The home page is broken for some reason and I don't know how to change the URLs for pages which feels like something I should know how to do by now! So today I will fix the home page, which seems to be an issue with a piece of code not running that shouldn't run on that page so I just have to stop it from running on that page. I'd also like to organize all the code by page, but that could create issues with the code that is used more than once. AFter I fix that, I want to find out how to give the pages better urls than index.html. I imagine that'll come in handy to know some day. Then I want to finish the about me page. The code that's breaking the home page is what I want to run on the about me page, but it runs before the page is loaded then when the page is loaded it disapears. I think it's because I have it running after someone clicks the link button. I think it'll fix both issues if I run the function within an if statement saying if an element that is on the about page exists, run this code. Then I will move on to the portfolio page. I'm going to go through my repos (Currently 21) and take screenshots and store all the information in an array. I want to link to their netlify sites too. I think it'll be pretty straight forward. If I have any time left I will submit my journal (I might wait until I don't have any placeholder info) and begin the advanced javascript course I said I'd test.",
        image: "./images/dylan-gillis-laptop-on-table.jpg",
        alt: "A laptop sitting on a octogonal wooden table in the dark with a cacti in front of it food and a cup to it's left and a bottle to it's right.",
        id: "7",
    },
    {
        date: "July 22, 2024",
        title: "Final Touches on the Learning Journal",
        content: "I forgot to log it but I totally coded yesterday. Today I am still working on the Learning Journal. I don't like the hover effect on the header so I'd like to change that. Maybe blur the image instead of make it black and white, and make the header slightly larger. Still workshopping that. I'd also like to make the hover on the posts slightly less subtle Just darker colors should work. For the About page I need to make sure the selected post doesn't show up in the recent posts. I am not sure why it isn't working, I have it set to if (postId !== selectedPostId) but it shows it anyways. I'll have to think about that one. I also want a little more space between the photo and header information. In the footer I'd like to add some contact information. On the portfolio, I almost kind of got the grid to work but it breaks the further down you scroll. It's trying to get the images to fit but I don't want it to destroy the image to make it fit. Grid is still not my forte so I'm not sure how to fix this. I want to style it too. I'm thinking jsut the images, no borders, with a title at the top and the tags at the bottom. Not sure what to do about getting the title to be viewable though. I need a background, but that looks cheap. I also want to center the last post when it's on tablet view. After that I'd say the project is done. I'd just need one more entry for it to look alright. Then I have to try to keep up posting here. If I get done with time to spare I will start the advanced Javascript.",
        image: "./images/muhammad-rahim-person-painting.jpg",
        alt: "A man sitting in the dark on a laptop.",
        id: "8",
    },
    {
        date: "July 16, 2024",
        title: "Last One",
        content: "I have been coding I swear, I code so much. I'm so tired. At least I got back to this before it had been a whole month! Small wins! Now I will have a platform for this though. I am making a new site, it's called Learning Journal. I am supposed to have a bunch of posts on it, and since I want it to be unique, I will write the posts. Coding has been good. I got pretty depressed for a while there, but luckily my coding buddy, Fadumo, kept me in line and I coded every day. Every. Single. Day. Which is a good thing, but I won't lie, I miss my free time. That's ok, it was actually pretty fun coding last night. I was just learning but I finished a module and am ending it with this solo project. Things are looking up, go team!!",
        image: "./images/awmleer-I--person-at-laptop.jpg",
        alt: "A man sitting in the dark on a laptop.",
        id: "9",
    },
]