export const projects = [
    {
        name: "Rat Counter",
        github: "https://github.com/Raehale/rat-counter",
        link: "https://dazzling-taffy-b72679.netlify.app/",
        screenshot: "./projects/rat-counter.png",
        description: "An app for a user to count how many rats they see each day.",
        id: 1,
        tags: ["CSS", "HTML", "Javascript", "App"],
    },
    {
        name: "Happy Birthday Site",
        github: "https://github.com/Raehale/happy-birthday-site",
        link: "https://gentle-bienenstitch-a31d58.netlify.app/",
        screenshot: "./projects/birthday-gifts.png",
        description: "A website displaying birthday GIFts for my rats.",
        id: 2,
        tags: ["CSS", "HTML", "Website"],
    },
    {
        name: "Home Town",
        github: "https://github.com/Raehale/home-town",
        link: "https://aquamarine-empanada-f3f2ed.netlify.app/",
        screenshot: "./projects/Visit-Missoula-MT-USA.png",
        description: "A website advertising my home town.",
        id: 3,
        tags: ["CSS", "HTML", "Website"],
    },
    {
        name: "Score Board",
        github: "https://github.com/Raehale/score-board",
        link: "https://gilded-starship-91d8a9.netlify.app/",
        screenshot: "./projects/Score-Board.png",
        description: "An app that tracks the scores of two teams.",
        id: 4,
        tags: ["CSS", "HTML", "Javascript", "App"],
    },
    {
        name: "Twitter Copy",
        github: "https://github.com/Raehale/twitter-copy",
        link: "https://twitter-copy-rae.netlify.app/",
        screenshot: "./projects/twitter-sux",
        description: "A copy of twitter with a login ability.",
        id: 5,
        tags: ["CSS", "HTML", "Javascript", "WIP", "App"],
    },
    {
        name: "Notes Site",
        github: "https://github.com/Raehale/notes-site",
        link: "https://scrimba-code-notes.netlify.app/",
        screenshot: "./projects/Study-Notes.png",
        description: "A website displaying all my notes.",
        id: 6,
        tags: ["CSS", "HTML", "Javascript", "Website"],
    },
    {
        name: "Add To List",
        github: "https://github.com/Raehale/add-to-list",
        link: "https://add-to-list-raehaley.netlify.app/",
        screenshot: "./projects/Add-to-List.png",
        description: "An app using firebase to create and manage a list. It will have multiple list options.",
        id: 7,
        tags: ["CSS", "HTML", "Javascript", "WIP", "App"],
    },
    {
        name: "Pet Pic Picker",
        github: "https://github.com/Raehale/pet-pic-picker",
        link: "https://pet-pic-picker.netlify.app/",
        screenshot: "./projects/Pet-Pics.png",
        description: "An app you can upload images of your pets and it will randomly generate a pet from the one you selected.",
        id: 8,
        tags: ["CSS", "HTML", "Javascript", "WIP", "App"],
    },
    {
        name: "Oldagram",
        github: "https://github.com/Raehale/oldagram",
        link: "https://lively-syrniki-b7d7af.netlify.app/",
        screenshot: "./projects/Oldagram.png",
        description: "A site showing the old version of instagram.",
        id: 9,
        tags: ["CSS", "HTML", "Javascript", "WIP", "App"],
    },
    {
        name: "Endorsements",
        github: "https://github.com/Raehale/endorsements",
        link: "https://endorsements-raehaley.netlify.app/",
        screenshot: "./projects/We-are-the-Champions.png",
        description: "A firebase app where users can write an endorsement to another user.",
        id: 10,
        tags: ["CSS", "HTML", "Javascript", "App"],
    },
    {
        name: "Business Card",
        github: "https://github.com/Raehale/business-card",
        link: "",
        screenshot: "./projects/",
        description: "",
        id: 11,
        tags: ["CSS", "HTML", "Website"],
    },
    {
        name: "Unit Conversion",
        github: "https://github.com/Raehale/unit-conversion",
        link: "https://fluffy-gumption-cfc0a9.netlify.app/",
        screenshot: "./projects/fluffy-gumption-cfc0a9-netlify-app.png",
        description: "An app that converts Metric and Imperial units.",
        id: 12,
        tags: ["CSS", "HTML", "Javascript", "App"],
    },
    {
        name: "Password Generator",
        github: "https://github.com/Raehale/password-generator",
        link: "https://moonlit-belekoy-587d28.netlify.app/",
        screenshot: "./projects/Generate-a-Random-Password.png",
        description: "An app that randomly generates a password.",
        id: 13,
        tags: ["CSS", "HTML", "Javascript", "App"],
    },
    {
        name: "Tabs Tracker",
        github: "https://github.com/Raehale/tab-tracker",
        link: "chrome://extensions/?id=hombgpfeadgajodedjjgjjeihmgbokkk",
        screenshot: "./projects/tab-saver.png",
        description: "A google extention that creates a list of sites you add to it to review later.",
        id: 14,
        tags: ["CSS", "HTML", "Javascript", "Extention"],
    },
    {
        name: "Best Fictional Rat",
        github: "https://github.com/Raehale/best-fictional-rat",
        link: "https://best-fictional-rat.netlify.app/",
        screenshot: "./projects/Best-Fictional-Rat-Award-Site.png",
        description: "A website made mobile first giving an award for best fictional rat.",
        id: 15,
        tags: ["CSS", "HTML", "Website"],
    },
    {
        name: "Mobile Restaurant Menu",
        github: "https://github.com/Raehale/mobile-restaurant-menu",
        link: "https://mobile-restaurant-menu-raehaley.netlify.app/",
        screenshot: "./projects/Mobile-restaurant-Menu.png",
        description: "An app for ordering from a restaurant, paying, and leaving a review.",
        id: "6",
        tags: ["CSS", "HTML", "Javascript", "App"],
    },
    {
        name: "Ratify Me",
        github: "https://github.com/Raehale/ratify-me",
        link: "https://ratify-me.netlify.app/",
        screenshot: "./projects/Ratify-Me.png",
        description: "It will work as a site that adds a random rat image to an image you upload.",
        id: "5",
        tags: ["CSS", "HTML", "WIP", "App"],
    },
    {
        name: "Rat News",
        github: "https://github.com/Raehale/Rat-News",
        link: "https://rat-news.netlify.app/",
        screenshot: "./projects/RatNews.png",
        description: "A website displaying fake articles about rats to display a grid layout.",
        id: "4",
        tags: ["CSS", "HTML", "Website"],
    },
    {
        name: "Learning Journal",
        github: "https://github.com/Raehale/Learning-Journal",
        link: "https://learning-journal-rh.netlify.app/",
        screenshot: "./projects/My-Learning-Journal.png",
        description: "A simple website to show my journey as a front end developer.",
        id: "2",
        tags: ["CSS", "HTML", "Javascript", "Website"],
    },
    {
        name: "Best bank",
        github: "https://github.com/Raehale/Best-Bank",
        link: "https://best-bank-group.netlify.app/",
        screenshot: "./projects/Best-Bank.png",
        description: "This is a group project done with two others, Fadumo and Guiseppe, that displays a bank statement page.",
        id: 1,
        tags: ["CSS", "HTML", "Javascript", "Website"],
    },
    // {
    //     name: "",
    //     github: "",
    //     link: "",
    //     screenshot: "",
    //     description: "",
    //     id: "",
        // tags: [],
    // },
]